### PR TITLE
Keep existing dates fixes #1.

### LINKED ISSUE #1: Option for setting missing dates only
I think it's a valid use case to only fill in "missing" (zero) end dates for courses.

### PR DESCRIPTION
**Pull request by lucaboesch**
Also redefined some testing variables so they correspond to the things tested.

### CODE REVIEW

**Comment by lucaboesch** [comment]
I've rebased that branch to current master.

**Comment by lucaboesch** [comment]
Rebased to master.

**Comment by lucaboesch** [comment]
I've slightly revisited the PHPUnit tests which had some weird titles/comments not describing what the functions were about to do and amended some variables names which didn't say what they were containing (e.g. a set $coursesnoenddate containing courses which effectively were supposed to have enddates indeed).
I hope that was all right, otherwise just skip.

Best,
Luca

**Comment by andyzito** [comment]
Hi Luca,

I may be missing something, but I don't see where in the code we're setting dates on courses which actually don't have end dates. That is, in `set_dates.php`, when `$keepexisting` is set to `1`, it looks like the dates are _never_ altered. Whereas we _do_ want the end date to be set if it wasn't set before.

**Comment by andyzito** [comment]
This pull request has gotten into a weird place in Git. I've fixed a few things and made a new pull request: https://github.com/LafColITS/moodle-tool_coursedates/pull/14.

Thank you for your contribution @lucaboesch !

**Pull request closed without merging**
